
package com.example.practice716client.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProductService", targetNamespace = "http://service.practice716service.example.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProductService {


    /**
     * 
     * @return
     *     returns java.util.List<com.example.practice716client.service.Product>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllProducts", targetNamespace = "http://service.practice716service.example.com/", className = "com.example.practice716client.service.GetAllProducts")
    @ResponseWrapper(localName = "getAllProductsResponse", targetNamespace = "http://service.practice716service.example.com/", className = "com.example.practice716client.service.GetAllProductsResponse")
    @Action(input = "http://service.practice716service.example.com/ProductService/getAllProductsRequest", output = "http://service.practice716service.example.com/ProductService/getAllProductsResponse")
    public List<Product> getAllProducts();

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns com.example.practice716client.service.Product
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sellProduct", targetNamespace = "http://service.practice716service.example.com/", className = "com.example.practice716client.service.SellProduct")
    @ResponseWrapper(localName = "sellProductResponse", targetNamespace = "http://service.practice716service.example.com/", className = "com.example.practice716client.service.SellProductResponse")
    @Action(input = "http://service.practice716service.example.com/ProductService/sellProductRequest", output = "http://service.practice716service.example.com/ProductService/sellProductResponse")
    public Product sellProduct(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addProduct", targetNamespace = "http://service.practice716service.example.com/", className = "com.example.practice716client.service.AddProduct")
    @ResponseWrapper(localName = "addProductResponse", targetNamespace = "http://service.practice716service.example.com/", className = "com.example.practice716client.service.AddProductResponse")
    @Action(input = "http://service.practice716service.example.com/ProductService/addProductRequest", output = "http://service.practice716service.example.com/ProductService/addProductResponse")
    public boolean addProduct(
        @WebParam(name = "arg0", targetNamespace = "")
        Product arg0);

}
